### ISSUE TITLE
Cambiar usuario de administrador a no administrador y viceversa

### ISSUE THREAD

**Issue by Adrian-Garcia** [APIStear/FETEC-News#12]
[RF-10](https://docs.google.com/document/d/1_JSHYARjcf3UIS-ZKmdxzodX1YjL4-FlpRwfkFd4DoI/edit#bookmark=id.z5nrjw2cdz99)

## Descripción
Usuarios administradores pueden hacer que un usuario normal se convierta en usuario administrador y viceversa

## Permisos de quien ve
Administradores

**Comment by PauCamaraV** [comment]
Este requerimiento ya no aplicara
